stored_representations: "/workspace/mergekit/representations/stored_representations"

metrics:
 cosine_similarity: true
 mse: true
 linearity_score: true
 cka: true
 t-sne: true

analysis_type: "comparison"
comparison_type: "all"