representation_paths:
- "/Users/elliotstein/Documents/Arcee/mergekit/representations/stored_representations/Representations_Qwen_Qwen2-7B-Instruct_microsoft_orca-math-word-problems-200k_4000.h5"
- "/Users/elliotstein/Documents/Arcee/mergekit/representations/stored_representations/Representations_arcee-ai_qwen2-7b-math-tess_microsoft_orca-math-word-problems-200k_4000.h5"

metrics:
 cosine_similarity: true
 mse: false
 linearity_score: false
 cka: false
 t-sne: false

analysis_type: "individual"
comparison_type: "block"